/* MeryCon — contenido de referencia (genérico, sin datos personales).
   Los datos de la paciente NO van aquí: se importan desde un archivo aparte. */

const LEVELS = {
  1: { nombre: 'Base', desc: 'Sentada o tumbada, con apoyo total. Rutina inicial del Excel.' },
  2: { nombre: 'Activación', desc: 'Más control y pequeñas cargas, aún con mucho apoyo.' },
  3: { nombre: 'Fuerza funcional', desc: 'De pie con apoyo y menos ayuda de los brazos. Comentar con la fisio antes de empezar.' },
  4: { nombre: 'Control y equilibrio', desc: 'Escalón bajo, equilibrio con apoyo cercano. Requiere visto bueno de la fisio.' },
  5: { nombre: 'Autonomía', desc: 'Tareas cercanas a la vida diaria. Solo con visto bueno de la fisio.' }
};

const BLOQUES = {
  resp: 'Respiración', tobillo: 'Tobillo y pantorrilla', rodilla: 'Rodilla', cadera: 'Cadera',
  core: 'Control lumbar / core', levantarse: 'Levantarse', equilibrio: 'Equilibrio', escalon: 'Escalones',
  movilidad: 'Movilidad de tronco', postura: 'Espalda alta / postura'
};

/* Cada ejercicio: previo = id del ejercicio que hay que dominar para desbloquearlo.
   fisio = true → conviene confirmar con la fisioterapeuta antes de empezarlo. */
const EXERCISES = [
  // ---------------- NIVEL 1 (rutina del Excel) ----------------
  { id: 'r1', nivel: 1, bloque: 'resp', orden: 1, min: 1.5, nombre: 'Respiración diafragmática',
    objetivo: 'Activar la respiración y bajar el tono muscular antes de empezar.',
    posicion: 'Sentada en silla con respaldo, o tumbada boca arriba con rodillas dobladas.',
    ejecucion: 'Inhalar por la nariz llevando el aire al abdomen (que se eleve la tripa, no el pecho); exhalar despacio por la boca.',
    dosis: '5-8 respiraciones (1-2 min).', respiracion: 'Inhalar 3-4 s, exhalar 4-6 s.',
    esperadas: 'Relajación progresiva, ninguna molestia.', parar: 'Mareo, ahogo, aumento de ansiedad.',
    errores: 'Respirar rápido o forzar la respiración.', facil: 'Respiración natural sin contar tiempos.',
    progresion: 'Respiración con activación abdominal suave.' },
  { id: 't1', nivel: 1, bloque: 'tobillo', orden: 2, min: 1, nombre: 'Movilidad de tobillos (bombeo)',
    objetivo: 'Mantener movilidad y activar la circulación en las piernas.',
    posicion: 'Sentada en silla, pies apoyados en el suelo.',
    ejecucion: 'Subir y bajar las puntas de los pies alternando ambos pies.',
    dosis: '10-15 repeticiones por pie (1 min).', respiracion: 'Libre y continua, sin retenerla.',
    esperadas: 'Ligera sensación de movimiento, nada doloroso.', parar: 'Dolor agudo, calambre que no cede.',
    errores: 'Hacerlo muy rápido y sin control.', facil: 'Menos recorrido o más despacio.',
    progresion: 'Círculos de tobillo en ambos sentidos.' },
  { id: 'k1', nivel: 1, bloque: 'rodilla', orden: 3, min: 1.5, nombre: 'Extensión de rodilla sentada',
    objetivo: 'Mantener el rango de movimiento de la rodilla sin carga.',
    posicion: 'Sentada en silla con respaldo.',
    ejecucion: 'Estirar una rodilla llevando la pierna hacia delante y volver a doblarla apoyando el pie.',
    dosis: '8-10 repeticiones por pierna (1-2 min).', respiracion: 'Exhalar al estirar, inhalar al volver.',
    esperadas: 'Tirantez leve, nunca dolor agudo en la rodilla.', parar: 'Dolor punzante, bloqueo, hinchazón inmediata.',
    errores: 'Estirar de golpe o con impulso.', facil: 'No estirar del todo; solo hasta donde no moleste.',
    progresion: 'Añadir una pausa de 2-3 s con la pierna estirada.' },
  { id: 'h1', nivel: 1, bloque: 'cadera', orden: 4, min: 1.5, nombre: 'Elevación de rodilla sentada',
    objetivo: 'Movilizar la cadera en un rango tolerable sin cargar la zona lumbar.',
    posicion: 'Sentada en silla con respaldo, manos en el asiento o en los muslos.',
    ejecucion: 'Elevar una rodilla suavemente hacia el pecho y bajarla con control.',
    dosis: '6-8 repeticiones por pierna (1-2 min).', respiracion: 'Exhalar al subir, inhalar al bajar.',
    esperadas: 'Activación suave de cadera/abdomen, sin dolor lumbar.', parar: 'Dolor lumbar que aumenta, dolor que baja a la pierna, pérdida de equilibrio.',
    errores: 'Arquear la espalda en lugar de mover la cadera.', facil: 'Subir menos la rodilla o ayudarse con las manos.',
    progresion: 'Apretar un cojín entre las rodillas (activación de cadera).' },
  { id: 'c1', nivel: 1, bloque: 'core', orden: 5, min: 2, nombre: 'Báscula pélvica',
    objetivo: 'Activar la musculatura profunda del abdomen y movilizar suavemente la zona lumbar.',
    posicion: 'Tumbada boca arriba en la cama, rodillas dobladas, pies apoyados.',
    ejecucion: 'Aplanar suavemente la zona lumbar contra la cama contrayendo el abdomen bajo, mantener y soltar.',
    dosis: '8-10 repeticiones manteniendo 3-5 s (2 min).', respiracion: 'Exhalar al contraer, inhalar al soltar.',
    esperadas: 'Activación suave del abdomen, nunca dolor.', parar: 'Dolor lumbar que aumenta; hormigueo o adormecimiento que aparece o empeora.',
    errores: 'Contraer demasiado fuerte o levantar la pelvis.', facil: 'Contracción más suave, movimiento más pequeño.',
    progresion: 'Puente de glúteos parcial (cuando lo indique la fisio).' },
  { id: 's1', nivel: 1, bloque: 'levantarse', orden: 6, min: 1.5, nombre: 'Levantarse y sentarse con apoyo',
    objetivo: 'Mejorar la fuerza de piernas y la capacidad de levantarse con seguridad.',
    posicion: 'Sentada en silla firme con reposabrazos o con apoyo estable delante (mesa, encimera).',
    ejecucion: 'Levantarse apoyándose con los brazos, controlar el movimiento y volver a sentarse despacio.',
    dosis: '3-5 repeticiones con pausa entre cada una (1-2 min).', respiracion: 'Exhalar al levantarse, inhalar al sentarse.',
    esperadas: 'Esfuerzo en piernas, ligera fatiga, sin dolor agudo.', parar: 'Mareo al levantarse, dolor agudo, pérdida de equilibrio, piernas que fallan.',
    errores: 'Levantarse de golpe o dejarse caer al sentarse.', facil: 'Silla más alta, más apoyo de brazos, 2-3 repeticiones.',
    progresion: 'Reducir el apoyo de los brazos (una mano).' },
  { id: 'b1', nivel: 1, bloque: 'equilibrio', orden: 7, min: 1.5, nombre: 'Transferencia de peso con apoyo',
    objetivo: 'Trabajar el equilibrio de forma segura para ganar confianza.',
    posicion: 'De pie, con apoyo firme de ambas manos en encimera, silla fija o pared.',
    ejecucion: 'Pasar el peso suavemente de un pie al otro, sin soltar las manos.',
    dosis: '6-8 repeticiones por lado (1-2 min).', respiracion: 'Libre y continua.',
    esperadas: 'Sensación de control, ligera activación de piernas.', parar: 'Mareo, sensación de caída, aumento del miedo.',
    errores: 'Soltar el apoyo antes de sentirse segura.', facil: 'Movimiento más pequeño, ambas manos bien apoyadas.',
    progresion: 'Marcha en el sitio con apoyo.' },

  // ---------------- NIVEL 2 ----------------
  { id: 'r2', nivel: 2, bloque: 'resp', previo: 'r1', min: 1.5, nombre: 'Respiración con activación abdominal',
    objetivo: 'Coordinar respiración y faja abdominal profunda.',
    posicion: 'Tumbada boca arriba con rodillas dobladas, o sentada.',
    ejecucion: 'Al exhalar, meter suavemente el ombligo hacia dentro (como al abrocharse un pantalón ajustado) sin mover la espalda; soltar al inhalar.',
    dosis: '6-8 respiraciones.', respiracion: 'Exhalación larga mientras activa.',
    esperadas: 'Ligera tensión abdominal, sin dolor.', parar: 'Dolor lumbar, mareo, ahogo.',
    errores: 'Aguantar la respiración o apretar demasiado.', facil: 'Volver a respiración diafragmática simple.',
    progresion: 'Mantener la activación mientras mueve los talones (talones alternos tumbada).' },
  { id: 't2', nivel: 2, bloque: 'tobillo', previo: 't1', min: 1, nombre: 'Círculos de tobillo',
    objetivo: 'Movilidad completa del tobillo.', posicion: 'Sentada, pie ligeramente levantado o apoyado en el talón.',
    ejecucion: 'Dibujar círculos lentos con la punta del pie en ambos sentidos.',
    dosis: '8 círculos en cada sentido por pie.', respiracion: 'Libre.',
    esperadas: 'Movimiento suave.', parar: 'Dolor agudo o calambre.', errores: 'Mover toda la pierna en lugar del tobillo.',
    facil: 'Apoyar el talón en el suelo y hacer círculos pequeños.', progresion: 'Elevación de talones de pie con apoyo.' },
  { id: 'k2', nivel: 2, bloque: 'rodilla', previo: 'k1', min: 2, nombre: 'Extensión de rodilla con pausa',
    objetivo: 'Fortalecer el cuádriceps sin carga articular.', posicion: 'Sentada en silla con respaldo.',
    ejecucion: 'Estirar la rodilla, apretar el muslo 3 s con la pierna estirada y bajar despacio.',
    dosis: '8-10 repeticiones por pierna.', respiracion: 'Exhalar al estirar y mantener; inhalar al bajar.',
    esperadas: 'Esfuerzo en el muslo.', parar: 'Dolor punzante o bloqueo de rodilla.',
    errores: 'Bloquear la rodilla de golpe; echarse hacia atrás.', facil: 'Pausa de 1 s o menos recorrido.',
    progresion: 'Pausa de 5 s; más adelante lastre ligero si la fisio lo indica.' },
  { id: 'h2', nivel: 2, bloque: 'cadera', previo: 'h1', min: 1.5, nombre: 'Apretar cojín entre las rodillas',
    objetivo: 'Activar la musculatura de la cadera y la faja abdominal.', posicion: 'Sentada, cojín o toalla doblada entre las rodillas.',
    ejecucion: 'Apretar el cojín suavemente 5 s y soltar.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al apretar.',
    esperadas: 'Activación en la cara interna de los muslos.', parar: 'Dolor en ingle o cadera que aumenta.',
    errores: 'Apretar al máximo; aguantar la respiración.', facil: 'Apretar más suave y 3 s.',
    progresion: 'Separar rodillas contra la resistencia de las manos, o abducción de pie con apoyo.' },
  { id: 'c2', nivel: 2, bloque: 'core', previo: 'c1', fisio: true, min: 2, nombre: 'Puente de glúteos parcial',
    objetivo: 'Activar glúteos y extensores de cadera con poca carga lumbar.',
    posicion: 'Tumbada boca arriba en cama firme, rodillas dobladas, pies apoyados a la anchura de las caderas.',
    ejecucion: 'Hacer la báscula pélvica y elevar la pelvis solo unos centímetros; bajar despacio.',
    dosis: '6-8 repeticiones.', respiracion: 'Exhalar al subir, inhalar al bajar.',
    esperadas: 'Trabajo en glúteos y parte posterior del muslo.', parar: 'Dolor lumbar que aumenta o que baja a la pierna; hormigueo.',
    errores: 'Subir demasiado arqueando la zona lumbar.', facil: 'Volver a báscula pélvica con más mantenimiento.',
    progresion: 'Puente con pausa de 5 s arriba.' },
  { id: 'm1', nivel: 2, bloque: 'movilidad', previo: 'c1', min: 1.5, nombre: 'Balanceo pélvico sentada',
    objetivo: 'Movilidad suave de la zona lumbar sin carga.', posicion: 'Sentada en el borde de una silla estable, pies apoyados.',
    ejecucion: 'Rodar la pelvis hacia delante (arquear un poco) y hacia atrás (redondear un poco), en rango pequeño.',
    dosis: '8-10 repeticiones lentas.', respiracion: 'Inhalar hacia delante, exhalar hacia atrás.',
    esperadas: 'Movimiento cómodo en la zona lumbar.', parar: 'Si una de las dos direcciones aumenta el dolor de pierna o el hormigueo → dejar esa dirección y anotarlo para la fisio.',
    errores: 'Mover los hombros en lugar de la pelvis.', facil: 'Recorrido más pequeño.',
    progresion: 'Mantener recorrido cómodo; la fisio puede indicar una dirección preferente.' },
  { id: 'p1', nivel: 2, bloque: 'postura', previo: 'r1', min: 1, nombre: 'Retracción escapular sentada',
    objetivo: 'Activar la espalda alta y mejorar la postura.', posicion: 'Sentada con la espalda separada del respaldo.',
    ejecucion: 'Juntar suavemente los omóplatos hacia atrás y abajo, mantener 3 s y soltar.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al juntar.',
    esperadas: 'Ligero trabajo entre los omóplatos.', parar: 'Dolor de cuello u hombro.',
    errores: 'Subir los hombros hacia las orejas.', facil: 'Menos tiempo de mantenimiento.',
    progresion: 'Remo con banda elástica o toalla.' },
  { id: 's2', nivel: 2, bloque: 'levantarse', previo: 's1', min: 1.5, nombre: 'Levantarse con apoyo de una mano',
    objetivo: 'Reducir la dependencia de los brazos al levantarse.', posicion: 'Silla firme con reposabrazos; apoyo estable al lado.',
    ejecucion: 'Echar el tronco ligeramente adelante, apoyar solo una mano y levantarse; sentarse despacio.',
    dosis: '4-6 repeticiones con pausa.', respiracion: 'Exhalar al levantarse.',
    esperadas: 'Más trabajo de piernas.', parar: 'Mareo, dolor agudo, piernas que fallan.',
    errores: 'Impulsarse con balanceo; dejarse caer.', facil: 'Silla más alta (cojín) o volver a dos manos.',
    progresion: 'Levantarse sin brazos desde silla alta.' },
  { id: 't3', nivel: 2, bloque: 'tobillo', previo: 't2', min: 1.5, nombre: 'Elevación de talones con apoyo',
    objetivo: 'Fortalecer pantorrillas para la marcha y el equilibrio.', posicion: 'De pie frente a una encimera, ambas manos apoyadas.',
    ejecucion: 'Subir de puntillas despacio y bajar con control.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al subir.',
    esperadas: 'Trabajo en pantorrillas.', parar: 'Mareo, calambre, inestabilidad.',
    errores: 'Soltar las manos; subir con impulso.', facil: 'Subir solo un poco.',
    progresion: 'Mismo ejercicio con una sola mano de apoyo.' },
  { id: 'b2', nivel: 2, bloque: 'equilibrio', previo: 'b1', min: 1.5, nombre: 'Marcha en el sitio con apoyo',
    objetivo: 'Equilibrio dinámico y confianza.', posicion: 'De pie frente a una encimera, ambas manos apoyadas.',
    ejecucion: 'Levantar alternativamente los pies del suelo, como caminando en el sitio, a ritmo lento.',
    dosis: '30-60 s.', respiracion: 'Libre.',
    esperadas: 'Sensación de control.', parar: 'Mareo, miedo a caerse, dolor que baja a la pierna.',
    errores: 'Levantar mucho la rodilla o ir rápido.', facil: 'Solo levantar el talón, sin despegar la punta.',
    progresion: 'Pies juntos con apoyo de una mano.' },

  // ---------------- NIVEL 3 ----------------
  { id: 'c5', nivel: 3, bloque: 'core', previo: 'r2', min: 2, nombre: 'Talones alternos tumbada',
    objetivo: 'Control abdominal con movimiento de piernas.', posicion: 'Tumbada boca arriba, rodillas dobladas, pies apoyados.',
    ejecucion: 'Con el abdomen activado, deslizar un talón por la cama estirando la pierna y volver; alternar.',
    dosis: '6-8 por pierna.', respiracion: 'Exhalar al deslizar.',
    esperadas: 'Trabajo abdominal suave.', parar: 'Dolor lumbar o de pierna que aumenta.',
    errores: 'Arquear la espalda cuando se estira la pierna.', facil: 'Recorrido más corto.',
    progresion: 'Variante brazo-pierna contraria (dead bug suave), con visto bueno de la fisio.' },
  { id: 'c3', nivel: 3, bloque: 'core', previo: 'c2', fisio: true, min: 2, nombre: 'Puente de glúteos con pausa',
    objetivo: 'Fuerza de glúteos para levantarse y caminar.', posicion: 'Tumbada boca arriba, rodillas dobladas.',
    ejecucion: 'Elevar la pelvis hasta una altura cómoda, mantener 5 s y bajar vértebra a vértebra.',
    dosis: '6-8 repeticiones.', respiracion: 'Exhalar al subir; respirar normal durante la pausa.',
    esperadas: 'Trabajo de glúteos.', parar: 'Dolor lumbar o irradiado que aumenta; calambre.',
    errores: 'Arquear la zona lumbar; empujar con el cuello.', facil: 'Pausa de 2 s o puente parcial.',
    progresion: 'Puente con marcha alterna (nivel 5, con fisio).' },
  { id: 'a1', nivel: 3, bloque: 'cadera', previo: 'h2', min: 2, nombre: 'Almeja tumbada de lado',
    objetivo: 'Fortalecer el glúteo medio (estabilidad de cadera al caminar).',
    posicion: 'Tumbada de lado, cadera y rodillas dobladas, cojín entre las rodillas si molesta la cadera.',
    ejecucion: 'Manteniendo los pies juntos, separar la rodilla de arriba unos centímetros y bajar.',
    dosis: '8-10 por lado.', respiracion: 'Exhalar al abrir.',
    esperadas: 'Trabajo en el lateral de la cadera.', parar: 'Dolor de cadera que aumenta; dolor lumbar al estar de lado.',
    errores: 'Girar la pelvis hacia atrás.', facil: 'Abrir menos o hacerlo sentada (separar rodillas contra las manos).',
    progresion: 'Abducción de cadera de pie con apoyo.' },
  { id: 'h3', nivel: 3, bloque: 'cadera', previo: 'h2', min: 2, nombre: 'Abducción de cadera de pie con apoyo',
    objetivo: 'Fuerza lateral de cadera para la estabilidad.', posicion: 'De pie, ambas manos en una encimera.',
    ejecucion: 'Separar una pierna hacia el lado unos centímetros, sin inclinar el tronco, y volver.',
    dosis: '6-8 por pierna.', respiracion: 'Exhalar al separar.',
    esperadas: 'Trabajo en el lateral de la cadera.', parar: 'Dolor de cadera o lumbar que aumenta, inestabilidad.',
    errores: 'Inclinar el tronco hacia el lado contrario.', facil: 'Menos recorrido.',
    progresion: 'Pasos laterales junto a la encimera.' },
  { id: 'h4', nivel: 3, bloque: 'cadera', previo: 'h2', min: 2, nombre: 'Extensión de cadera de pie con apoyo',
    objetivo: 'Activar glúteos en posición de marcha.', posicion: 'De pie, ambas manos en una encimera, ligera inclinación adelante.',
    ejecucion: 'Llevar una pierna estirada ligeramente hacia atrás sin arquear la espalda y volver.',
    dosis: '6-8 por pierna.', respiracion: 'Exhalar al llevar atrás.',
    esperadas: 'Trabajo en glúteo.', parar: 'Dolor lumbar al llevar la pierna atrás; dolor irradiado.',
    errores: 'Arquear la zona lumbar para subir más.', facil: 'Recorrido muy pequeño.',
    progresion: 'Mantener 2 s atrás.' },
  { id: 'k4', nivel: 3, bloque: 'rodilla', previo: 'k2', min: 2, nombre: 'Flexión de rodilla de pie con apoyo',
    objetivo: 'Fortalecer la parte posterior del muslo.', posicion: 'De pie, ambas manos en una encimera.',
    ejecucion: 'Doblar una rodilla llevando el talón hacia el glúteo y bajar despacio.',
    dosis: '8 por pierna.', respiracion: 'Exhalar al doblar.',
    esperadas: 'Trabajo posterior del muslo.', parar: 'Dolor de rodilla punzante; calambre.',
    errores: 'Adelantar la cadera; ir rápido.', facil: 'Menos recorrido.',
    progresion: 'Pausa de 2 s arriba.' },
  { id: 's3', nivel: 3, bloque: 'levantarse', previo: 's2', min: 2, nombre: 'Levantarse sin brazos (silla alta)',
    objetivo: 'Levantarse sin depender de los brazos.', posicion: 'Silla firme y alta (o con cojín), brazos cruzados o en los muslos; apoyo cerca por seguridad.',
    ejecucion: 'Pies algo por detrás de las rodillas, tronco adelante, levantarse; sentarse despacio.',
    dosis: '5 repeticiones.', respiracion: 'Exhalar al levantarse.',
    esperadas: 'Esfuerzo moderado en piernas.', parar: 'Mareo, dolor agudo, piernas que fallan.',
    errores: 'Rodillas hacia dentro; caer al sentarse.', facil: 'Usar una mano.',
    progresion: 'Silla de altura normal, 8-10 repeticiones.' },
  { id: 'b3', nivel: 3, bloque: 'equilibrio', previo: 'b2', min: 1.5, nombre: 'Pies juntos con apoyo de una mano',
    objetivo: 'Equilibrio estático con menos base.', posicion: 'De pie junto a una encimera, una mano apoyada, la otra lista.',
    ejecucion: 'Juntar los pies y mantener la posición mirando al frente.',
    dosis: '3 × 20-30 s.', respiracion: 'Libre.',
    esperadas: 'Pequeños ajustes de equilibrio.', parar: 'Mareo, sensación de caída.',
    errores: 'Mirar al suelo; bloquear las rodillas.', facil: 'Pies un poco separados o dos manos.',
    progresion: 'Semitándem con apoyo cercano (con la fisio).' },
  { id: 'e1', nivel: 3, bloque: 'escalon', previo: 'b2', min: 1.5, nombre: 'Paso adelante y atrás con apoyo',
    objetivo: 'Preparar el gesto de subir escalones.', posicion: 'De pie junto a una encimera, una o dos manos apoyadas.',
    ejecucion: 'Dar un paso corto adelante, pasar el peso y volver; alternar piernas.',
    dosis: '6-8 por pierna.', respiracion: 'Libre.',
    esperadas: 'Control del peso.', parar: 'Inestabilidad, dolor de rodilla o cadera que aumenta.',
    errores: 'Pasos largos; girar el tronco.', facil: 'Paso más corto, dos manos.',
    progresion: 'Subir un escalón bajo con barandilla.' },
  { id: 'p2', nivel: 3, bloque: 'postura', previo: 'p1', min: 1.5, nombre: 'Remo con banda o toalla',
    objetivo: 'Fuerza de espalda alta.', posicion: 'Sentada, banda elástica sujeta a una puerta o una toalla que tira otra persona.',
    ejecucion: 'Tirar hacia atrás con los codos pegados al cuerpo juntando omóplatos; volver despacio.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al tirar.',
    esperadas: 'Trabajo en espalda alta.', parar: 'Dolor de hombro, cuello o lumbar.',
    errores: 'Encoger hombros; echarse hacia atrás.', facil: 'Banda más suave.',
    progresion: 'Más repeticiones o banda un poco más dura.' },

  // ---------------- NIVEL 4 ----------------
  { id: 'c6', nivel: 4, bloque: 'core', previo: 'c5', fisio: true, min: 2, nombre: 'Brazo y pierna contrarios tumbada (dead bug suave)',
    objetivo: 'Control lumbar con coordinación.', posicion: 'Tumbada boca arriba, rodillas dobladas, brazos hacia el techo.',
    ejecucion: 'Con el abdomen activado, deslizar un talón y llevar el brazo contrario hacia atrás; volver y alternar.',
    dosis: '5-6 por lado.', respiracion: 'Exhalar al alejar.',
    esperadas: 'Trabajo abdominal.', parar: 'Dolor lumbar, arqueo que no controla.',
    errores: 'Separar la zona lumbar de la cama.', facil: 'Solo piernas (talones alternos).',
    progresion: 'Más repeticiones con buen control.' },
  { id: 'k3', nivel: 4, bloque: 'rodilla', previo: 'k2', fisio: true, min: 2, nombre: 'Extensión de rodilla con lastre ligero',
    objetivo: 'Fuerza de cuádriceps progresiva.', posicion: 'Sentada, tobillera de 0,5-1 kg.',
    ejecucion: 'Estirar la rodilla, mantener 3 s y bajar despacio.',
    dosis: '8-10 por pierna.', respiracion: 'Exhalar al estirar.',
    esperadas: 'Esfuerzo en el muslo.', parar: 'Dolor de rodilla que aumenta o hinchazón al día siguiente.',
    errores: 'Lastre excesivo; movimiento brusco.', facil: 'Sin lastre.',
    progresion: 'Subir lastre solo si la fisio lo indica.' },
  { id: 'h5', nivel: 4, bloque: 'cadera', previo: 'h3', min: 2, nombre: 'Pasos laterales junto a la encimera',
    objetivo: 'Estabilidad lateral funcional.', posicion: 'De pie de cara a la encimera, manos apoyadas.',
    ejecucion: 'Dar pasos laterales cortos a lo largo de la encimera, ida y vuelta.',
    dosis: '3-4 idas y vueltas.', respiracion: 'Libre.',
    esperadas: 'Trabajo de cadera.', parar: 'Inestabilidad, dolor de cadera.',
    errores: 'Cruzar los pies; pasos largos.', facil: 'Menos distancia.',
    progresion: 'Más idas y vueltas.' },
  { id: 's4', nivel: 4, bloque: 'levantarse', previo: 's3', min: 2, nombre: 'Levantarse sin brazos (silla normal)',
    objetivo: 'Autonomía para levantarse de cualquier silla.', posicion: 'Silla de altura normal, brazos cruzados; apoyo cerca.',
    ejecucion: 'Levantarse y sentarse con control.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al levantarse.',
    esperadas: 'Esfuerzo en piernas.', parar: 'Mareo, dolor agudo, piernas que fallan.',
    errores: 'Impulso con el tronco; caer al sentarse.', facil: 'Silla alta.',
    progresion: 'Bajada lenta de 3 s.' },
  { id: 't4', nivel: 4, bloque: 'tobillo', previo: 't3', min: 1.5, nombre: 'Elevación de talones con una mano',
    objetivo: 'Fuerza de pantorrilla y equilibrio.', posicion: 'De pie junto a una encimera, una mano apoyada.',
    ejecucion: 'Subir de puntillas y bajar despacio.',
    dosis: '10-12 repeticiones.', respiracion: 'Exhalar al subir.',
    esperadas: 'Trabajo en pantorrilla.', parar: 'Inestabilidad, calambre.',
    errores: 'Balancearse.', facil: 'Dos manos.', progresion: 'Más repeticiones.' },
  { id: 'b4', nivel: 4, bloque: 'equilibrio', previo: 'b3', fisio: true, min: 1.5, nombre: 'Semitándem con apoyo cercano',
    objetivo: 'Equilibrio con base estrecha.', posicion: 'Junto a la encimera, una mano apoyada o rozando.',
    ejecucion: 'Colocar un pie medio adelantado (el talón a la altura del arco del otro) y mantener.',
    dosis: '3 × 15-30 s por lado.', respiracion: 'Libre.',
    esperadas: 'Ajustes de equilibrio.', parar: 'Mareo, sensación de caída.',
    errores: 'Mirar al suelo.', facil: 'Pies juntos.', progresion: 'Tándem completo con apoyo cercano.' },
  { id: 'e2', nivel: 4, bloque: 'escalon', previo: 'e1', fisio: true, min: 2, nombre: 'Subir un escalón bajo con barandilla',
    objetivo: 'Recuperar la capacidad de subir escaleras.', posicion: 'Frente a un escalón bajo (10-15 cm) con barandilla firme.',
    ejecucion: 'Subir con la pierna más fuerte, bajar con la más débil ("sube el bueno, baja el malo"); agarrada siempre.',
    dosis: '5-6 por lado.', respiracion: 'Exhalar al subir.',
    esperadas: 'Esfuerzo en muslo y glúteo.', parar: 'Dolor de rodilla punzante, inestabilidad, mareo.',
    errores: 'Soltar la barandilla; subir con impulso.', facil: 'Escalón más bajo o paso adelante en llano.',
    progresion: 'Subir y bajar 2-3 escalones.' },

  // ---------------- NIVEL 5 ----------------
  { id: 's5', nivel: 5, bloque: 'levantarse', previo: 's4', min: 2, nombre: 'Levantarse con bajada lenta',
    objetivo: 'Fuerza excéntrica y control al sentarse.', posicion: 'Silla normal, brazos cruzados.',
    ejecucion: 'Levantarse normal y sentarse contando 3 s de bajada.',
    dosis: '8-10 repeticiones.', respiracion: 'Exhalar al levantarse, inhalar al bajar.',
    esperadas: 'Esfuerzo moderado.', parar: 'Dolor de rodilla o lumbar que aumenta.',
    errores: 'Dejarse caer al final.', facil: 'Bajada de 2 s.', progresion: 'Mantener y usar como mantenimiento.' },
  { id: 'c4', nivel: 5, bloque: 'core', previo: 'c3', fisio: true, min: 2, nombre: 'Puente con marcha alterna',
    objetivo: 'Estabilidad de pelvis.', posicion: 'Tumbada boca arriba, en puente parcial.',
    ejecucion: 'Desde el puente, despegar un pie unos centímetros sin que caiga la pelvis; alternar.',
    dosis: '4-6 por lado.', respiracion: 'Libre, sin retener.',
    esperadas: 'Trabajo de glúteo y abdomen.', parar: 'Dolor lumbar o irradiado.',
    errores: 'Pelvis que se inclina.', facil: 'Puente con pausa.', progresion: 'Mantenimiento.' },
  { id: 'b5', nivel: 5, bloque: 'equilibrio', previo: 'b4', fisio: true, min: 1.5, nombre: 'Tándem con apoyo cercano',
    objetivo: 'Equilibrio avanzado con seguridad.', posicion: 'Junto a la encimera, mano rozando.',
    ejecucion: 'Un pie justo delante del otro (talón con punta) y mantener.',
    dosis: '3 × 15-30 s por lado.', respiracion: 'Libre.',
    esperadas: 'Ajustes de equilibrio.', parar: 'Mareo, sensación de caída.',
    errores: 'Soltarse del todo.', facil: 'Semitándem.', progresion: 'Caminar en línea junto a la encimera.' },
  { id: 'b6', nivel: 5, bloque: 'equilibrio', previo: 'b4', fisio: true, min: 1.5, nombre: 'Apoyo en un pie con ambas manos',
    objetivo: 'Equilibrio monopodal para escaleras y bordillos.', posicion: 'Frente a la encimera, ambas manos apoyadas.',
    ejecucion: 'Levantar un pie unos centímetros y mantener.',
    dosis: '3 × 5-10 s por lado.', respiracion: 'Libre.',
    esperadas: 'Trabajo de tobillo y cadera.', parar: 'Inestabilidad, dolor.',
    errores: 'Inclinar el tronco.', facil: 'Solo apoyar la punta del pie levantado.', progresion: 'Una mano.' },
  { id: 'e3', nivel: 5, bloque: 'escalon', previo: 'e2', fisio: true, min: 2, nombre: 'Subir y bajar 2-3 escalones',
    objetivo: 'Autonomía en escaleras.', posicion: 'Escalera con barandilla firme.',
    ejecucion: 'Subir y bajar 2-3 escalones agarrada, alternando o "sube el bueno, baja el malo".',
    dosis: '2-3 series.', respiracion: 'Libre.',
    esperadas: 'Esfuerzo en piernas.', parar: 'Dolor de rodilla, mareo, inestabilidad.',
    errores: 'Soltar la barandilla; prisa.', facil: 'Un solo escalón.', progresion: 'Más escalones según tolerancia.' },
  { id: 'm2', nivel: 5, bloque: 'movilidad', previo: 'm1', fisio: true, min: 1.5, nombre: 'Rodillas a un lado tumbada',
    objetivo: 'Movilidad de rotación muy suave de la columna.', posicion: 'Tumbada boca arriba, rodillas dobladas y juntas.',
    ejecucion: 'Dejar caer las rodillas un poco hacia un lado, en rango pequeño, y volver; alternar.',
    dosis: '6-8 por lado.', respiracion: 'Exhalar al bajar.',
    esperadas: 'Movilidad cómoda.', parar: 'Dolor lumbar o de pierna que aumenta.',
    errores: 'Bajar mucho o con impulso (evitar torsiones fuertes).', facil: 'Rango muy pequeño.', progresion: 'Mantenimiento.' }
];

/* Pruebas funcionales (cada 14 días). mejor: 'mas' | 'menos' | null */
const TESTS = [
  { id: 'sts30', nombre: 'Levantarse de la silla en 30 s', corto: 'Silla 30 s', unidad: 'rep', mejor: 'mas', grupo: 'Fuerza',
    como: 'Silla firme sin ruedas contra la pared. Contar cuántas veces se levanta del todo y se sienta en 30 s. Anotar si usa los brazos. Alguien al lado.',
    extra: { key: 'brazos', label: '¿Usó los brazos?', opts: ['No', 'Una mano', 'Ambas'] } },
  { id: 'caminata', nombre: 'Caminata continua tolerada', corto: 'Caminata', unidad: 'min', mejor: 'mas', grupo: 'Tolerancia',
    como: 'Minutos que camina a su ritmo hasta tener que parar por dolor/fatiga (no forzar). Anotar si el dolor mejora al sentarse o inclinarse.' },
  { id: 'pie', nombre: 'Tiempo de pie tolerado', corto: 'De pie', unidad: 'min', mejor: 'mas', grupo: 'Tolerancia',
    como: 'Minutos de pie (p. ej. en la cocina) hasta necesitar sentarse o apoyarse.' },
  { id: 'sentada', nombre: 'Tiempo sentada antes de cambiar de postura', corto: 'Sentada', unidad: 'min', mejor: 'mas', grupo: 'Tolerancia',
    como: 'Minutos sentada antes de que la molestia obligue a moverse.' },
  { id: 'piesjuntos', nombre: 'Pies juntos con apoyo ligero', corto: 'Pies juntos', unidad: 's', mejor: 'mas', grupo: 'Equilibrio', max: 30,
    como: 'Junto a una encimera con una mano rozando. Segundos con los pies juntos (máx. 30). Parar si hay mareo.' },
  { id: 'semitandem', nombre: 'Semitándem con apoyo cercano', corto: 'Semitándem', unidad: 's', mejor: 'mas', grupo: 'Equilibrio', max: 30, fisio: true,
    como: 'Solo si la fisio lo ve seguro. Un pie medio adelantado, mano cerca de la encimera. Segundos (máx. 30).' },
  { id: 'escalones', nombre: 'Escalones seguidos', corto: 'Escalones', unidad: 'esc.', mejor: 'mas', grupo: 'Escalones',
    como: 'Número de escalones que sube seguidos agarrada a la barandilla, sin dolor fuerte.',
    extra: { key: 'barandilla', label: 'Barandilla', opts: ['Con barandilla', 'Sin barandilla', 'Con ayuda de alguien'] } },
  { id: 'peso', nombre: 'Peso', corto: 'Peso', unidad: 'kg', mejor: null, grupo: 'Peso', step: 0.1,
    como: 'Misma báscula, por la mañana y con ropa similar.' }
];

/* Escala de autonomía: dificultad 0 (ninguna) - 10 (no puede) */
const AUTONOMY = [
  { id: 'cama', nombre: 'Girarse en la cama' },
  { id: 'levantarse', nombre: 'Levantarse de la silla' },
  { id: 'calcetines', nombre: 'Ponerse calcetines/zapatos' },
  { id: 'escaleras', nombre: 'Subir escaleras' },
  { id: 'casa', nombre: 'Tareas de casa' },
  { id: 'compra', nombre: 'Salir a comprar / recados' }
];

/* Señales de alarma (instrucciones del proyecto, apartados 9 y 28) */
const ALARMS = [
  { id: 'silla', nivel: 'urgente', texto: 'Adormecimiento nuevo en genitales, periné o zona de "silla de montar"' },
  { id: 'esfinter', nivel: 'urgente', texto: 'Pérdida nueva del control de orina o heces, o no poder orinar' },
  { id: 'episodio', nivel: 'urgente', texto: 'Nuevo episodio de adormecimiento de cintura para abajo o no poder caminar' },
  { id: 'fuerza', nivel: 'urgente', texto: 'Pérdida de fuerza nueva o que va a más' },
  { id: 'sensib', nivel: 'hoy', texto: 'Pérdida de sensibilidad extensa nueva' },
  { id: 'miccion', nivel: 'hoy', texto: 'Dificultad nueva importante para iniciar o mantener la micción' },
  { id: 'dolor', nivel: 'hoy', texto: 'Dolor súbito o muy diferente al habitual' },
  { id: 'fiebre', nivel: 'hoy', texto: 'Fiebre junto con dolor lumbar' },
  { id: 'caida', nivel: 'hoy', texto: 'Caída importante o golpe relevante' },
  { id: 'otro', nivel: 'hoy', texto: 'Otro síntoma que un profesional indicó como motivo de urgencia' }
];

const DOC_CATS = ['Resonancia / imagen', 'Traumatología', 'Neurocirugía', 'Neurología', 'Atención primaria', 'Fisioterapia', 'Análisis', 'Receta / medicación', 'Urgencias', 'Otros'];
const PROFESIONALES = ['Fisioterapeuta', 'Traumatología', 'Neurocirugía', 'Neurología', 'Médico de familia', 'Farmacéutico/a', 'Psiquiatría / Psicología', 'Otro'];
const MOMENTOS = [
  { id: 'manana', nombre: 'Mañana' },
  { id: 'mediodia', nombre: 'Mediodía' },
  { id: 'noche', nombre: 'Noche' },
  { id: 'demanda', nombre: 'Según necesidad' }
];
const ESTADOS_INFO = {
  confirmado: { nombre: 'Confirmado', color: 'green', desc: 'Documentado en informe' },
  referido: { nombre: 'Referido', color: 'blue', desc: 'Lo cuenta ella, sin informe' },
  interpretacion: { nombre: 'Interpretación', color: 'purple', desc: 'Lectura posible, no diagnóstico' },
  pendiente: { nombre: 'Pendiente', color: 'yellow', desc: 'Falta confirmar' },
  hipotesis: { nombre: 'Hipótesis', color: 'orange', desc: 'No tratar como hecho' }
};
const CLIN_CATS = ['Diagnóstico', 'Hallazgo de imagen', 'Síntoma', 'Antecedente', 'Tratamiento previo', 'Incertidumbre', 'Otro'];
